import { legalConfig } from './legal-config'
import type { LegalDocumentContent } from './types'

export const termsContent: LegalDocumentContent = {
  title: 'Termos de Uso e de Prestação de Serviços',
  subtitle: 'Versão 0.9 - minuta com campos e alternativas condicionais',
  version: legalConfig.terms.version,
  publishedAt: legalConfig.terms.publishedAt,
  effectiveAt: legalConfig.terms.effectiveAt,
  history: [
    {
      version: '0.9',
      publishedAt: '[DATA DE PUBLICAÇÃO]',
      summary: 'Minuta inicial baseada no pacote jurídico de 15 de julho de 2026; contém campos pendentes e não está aprovada para publicação definitiva.',
      material: true,
    },
  ],
  sections: [
    {
      id: 'aviso-essencial',
      title: 'Aviso essencial ao usuário',
      notice: 'As análises do BetIntel AI são estatísticas, informativas e probabilísticas. Não são recomendação de aposta, investimento ou orientação financeira. Probabilidades não garantem resultados. O BetIntel AI não recebe apostas, não guarda valores destinados a apostas e não controla eventos esportivos. Apostar envolve risco de perda parcial ou total. Uso exclusivo por maiores de 18 anos.',
    },
    {
      id: 'identificacao-do-fornecedor',
      title: '1. Identificação do fornecedor',
      paragraphs: [
        '1.1 Estes Termos regulam o acesso e o uso do BetIntel AI, disponibilizado por [RAZÃO SOCIAL OU NOME DO RESPONSÁVEL], inscrito no [CNPJ OU CPF] sob nº [CNPJ OU CPF], com endereço em [ENDEREÇO COMPLETO], [CIDADE E ESTADO], doravante “Fornecedor”.',
        '1.2 O domínio oficial é [DOMÍNIO]. Os canais oficiais são: suporte [E-MAIL DE SUPORTE], privacidade [E-MAIL DE PRIVACIDADE], telefone [TELEFONE] e demais canais indicados na Plataforma.',
        '1.3 O responsável pela prestação e faturamento do Serviço é [RESPONSÁVEL PELA PRESTAÇÃO]. Nenhuma referência à marca BetIntel AI deve ser interpretada como autorização para exploração de apostas de quota fixa, vínculo com a Secretaria de Prêmios e Apostas ou condição de instituição financeira.',
        '1.4 Em caso de divergência entre estes Termos e proposta empresarial assinada, ordem de serviço ou contrato específico, prevalecerá o instrumento específico apenas quanto ao objeto negociado, sem afastar direitos legais irrenunciáveis.',
      ],
    },
    {
      id: 'definicoes',
      title: '2. Definições',
      paragraphs: [
        '2.1 “Plataforma”: aplicação web, aplicativo, PWA, interfaces, painéis e domínios oficiais por meio dos quais o Serviço é disponibilizado.',
        '2.2 “Serviço”: acesso a funcionalidades de análise estatística e probabilística de partidas, recursos de conta, organização, suporte e demais funcionalidades descritas no Plano contratado.',
        '2.3 “Usuário”: pessoa natural que acessa a Plataforma. Pode ser Usuário Consumidor, Usuário Profissional, Administrador ou Membro de Organização.',
        '2.4 “Usuário Consumidor”: pessoa natural que utiliza o Serviço como destinatária final, sem prejuízo da aplicação do CDC quando reconhecida pela legislação ou pela situação concreta.',
        '2.5 “Usuário Profissional”: pessoa natural que utiliza o Serviço no contexto de atividade econômica ou profissional própria, observadas as normas cogentes aplicáveis.',
        '2.6 “Organização”: pessoa jurídica, entidade ou grupo contratante que gerencia assentos e membros em um ambiente compartilhado.',
        '2.7 “Proprietário da Organização”: usuário com poderes máximos de gestão, contratação, faturamento e transferência de propriedade.',
        '2.8 “Administrador”: usuário autorizado a convidar, remover e gerenciar membros e configurações dentro dos limites concedidos.',
        '2.9 “Membro”: usuário convidado para utilizar recursos da Organização. “Somente leitura” é o perfil que pode consultar, mas não alterar, configurações definidas pelo Plano.',
        '2.10 “Conta”: credencial individual e intransferível associada ao Usuário.',
        '2.11 “Assinatura”: contratação recorrente ou por período determinado que dá acesso a um Plano.',
        '2.12 “Plano”: conjunto de recursos, limites, assentos, ciclo de cobrança, suporte e preço exibidos antes da contratação.',
        '2.13 “Análise”: resultado estatístico produzido ou organizado pela Plataforma a partir de dados, regras, amostras e modelos.',
        '2.14 “Probabilidade”: estimativa numérica de ocorrência de determinado evento sob premissas e dados disponíveis, sem caráter de certeza ou garantia.',
        '2.15 “Predição” ou “Prognóstico”: inferência probabilística sobre evento futuro, sujeita a erro, viés, mudança de contexto e aleatoriedade.',
        '2.16 “Dados Esportivos”: informações sobre partidas, equipes, atletas, escalações, resultados, estatísticas, calendário e eventos relacionados, provenientes de fontes próprias, públicas ou licenciadas.',
        '2.17 “Fornecedor de Dados”: terceiro que licencia, transmite ou disponibiliza Dados Esportivos, infraestrutura ou informação utilizada pelo Serviço.',
        '2.18 “Conteúdo”: textos, tabelas, gráficos, probabilidades, relatórios, documentação, interfaces e materiais disponibilizados na Plataforma.',
        '2.19 “Recurso Gratuito”: funcionalidade disponibilizada sem cobrança, sujeita a limites e possível alteração.',
        '2.20 “Recurso Pago”: funcionalidade acessível mediante Assinatura ou contratação específica.',
        '2.21 “Dados Insuficientes”: estado em que a Plataforma não apresenta uma estimativa por ausência, baixa qualidade, inconsistência ou insuficiência de amostra, constituindo mecanismo de prudência e não necessariamente falha.',
      ],
    },
    {
      id: 'aceitacao',
      title: '3. Aceitação e formação do contrato',
      paragraphs: [
        '3.1 O uso da Plataforma depende da aceitação destes Termos e da Política de Privacidade por clickwrap, mediante checkbox não pré-marcado e links visíveis para os documentos.',
        '3.2 O aceite será registrado, quando juridicamente adequado e proporcional, com identificação do Usuário, Organização relacionada, finalidade do aceite, versão dos documentos, data e hora, endereço IP pseudonimizado, user agent, evidência do checkbox e hash ou cópia imutável da versão aceita.',
        '3.3 O Usuário declara ter tido oportunidade real de ler, baixar e armazenar os documentos antes de concluir o cadastro ou a contratação. Condições que não forem apresentadas de forma clara e acessível não serão consideradas incorporadas apenas por referência oculta.',
        '3.4 Alterações materiais em preço, renovação, responsabilidade do Usuário, tratamento de dados ou natureza do Serviço exigirão comunicação prévia e, quando necessário, novo aceite específico.',
        '3.5 A versão vigente e as versões anteriormente aceitas permanecerão disponíveis no histórico público e na Conta, pelo prazo legal e contratual aplicável.',
        '3.6 A utilização sem aceite não é permitida. O mero acesso a página pública informativa não implica contratação, salvo quanto às regras técnicas e de uso aceitável compatíveis com esse acesso.',
      ],
    },
    {
      id: 'elegibilidade',
      title: '4. Elegibilidade e restrição etária',
      paragraphs: [
        '4.1 O Serviço é destinado exclusivamente a pessoas com 18 anos ou mais. Menores de idade não podem criar Conta, acessar análises ou utilizar recursos da Plataforma, ainda que com autorização de responsável.',
        '4.2 Ao cadastrar-se, o Usuário declara possuir capacidade civil para contratar e fornece informações verdadeiras sobre sua idade.',
        '4.3 O Fornecedor poderá solicitar verificação razoável de idade ou identidade quando houver indício de fraude, inconsistência, risco regulatório ou necessidade de proteção do Usuário, limitando a coleta ao necessário e informando o tratamento na Política de Privacidade.',
        '4.4 Contas de menores ou criadas com identidade falsa poderão ser suspensas ou encerradas, com tratamento de valores pagos conforme a lei, a boa-fé e as circunstâncias do caso.',
        '4.5 A restrição etária não transforma o Serviço em casa de apostas. Ela constitui medida de proteção compatível com a natureza e o contexto de uso do produto.',
      ],
    },
    {
      id: 'natureza-probabilistica',
      title: '5. Natureza informativa e probabilística',
      paragraphs: [
        '5.1 As Análises são estatísticas e informativas, construídas a partir de dados históricos, amostras, regras, modelos computacionais e informações de terceiros.',
        '5.2 Probabilidades não representam certeza. Eventos esportivos são influenciados por fatores imprevisíveis, incluindo decisões humanas, escalações, lesões, arbitragem, clima, estratégia, erros, mudanças de regulamento e aleatoriedade.',
        '5.3 Resultados anteriores, taxas históricas, backtests ou desempenho em determinado período não garantem resultados futuros. Uma probabilidade elevada significa apenas uma estimativa sob as premissas disponíveis, e o evento pode não ocorrer.',
        '5.4 Modelos podem apresentar erros, vieses, limitações, mudanças de desempenho, overfitting, períodos de baixa precisão e resultados diferentes quando dados ou premissas mudam.',
        '5.5 A Plataforma poderá deixar de exibir uma Análise quando os dados forem insuficientes, inconsistentes, desatualizados ou inadequados. O estado “Dados Insuficientes” é medida de prudência, não promessa de cobertura integral.',
        '5.6 Quando disponibilizadas métricas de desempenho, serão indicados, na medida aplicável, período, amostra, metodologia, escopo, critérios de exclusão e limitações. O Usuário não deve extrapolar uma métrica para competições, mercados ou períodos diferentes.',
        '5.7 O Serviço não substitui fontes oficiais da competição, regulamentos, súmulas, escalações, resultados homologados ou verificação independente de informações sensíveis ao tempo.',
      ],
    },
    {
      id: 'ausencia-recomendacao',
      title: '6. Ausência de recomendação de aposta ou investimento',
      notice: 'NÃO É RECOMENDAÇÃO DE APOSTA, INVESTIMENTO OU ORIENTAÇÃO FINANCEIRA.',
      paragraphs: [
        '6.1 O Conteúdo não constitui indicação para comprar, vender, contratar, apostar ou realizar qualquer operação.',
        '6.2 O Serviço não presta consultoria financeira, de investimento, jurídica, tributária, contábil, médica ou psicológica, não representa corretora, instituição financeira, casa de apostas ou agente fiduciário.',
        '6.3 O Conteúdo não constitui promessa de lucro, garantia de acerto, garantia de retorno, estratégia personalizada de gestão financeira ou análise da capacidade econômica individual do Usuário.',
        '6.4 Nenhum percentual, alerta, classificação, selo, cor, ranking ou expressão utilizada na interface deve ser interpretado como instrução para apostar.',
        '6.5 O Fornecedor não assume dever fiduciário e não toma decisões pelo Usuário. A avaliação e a decisão são pessoais, independentes e devem considerar as condições financeiras, legais e emocionais do próprio Usuário.',
        '6.6 A existência de recurso de personalização estatística, quando houver, não transforma a Análise em recomendação individualizada, salvo se o funcionamento real exceder essa premissa, hipótese em que estes Termos devem ser revistos antes do lançamento.',
      ],
    },
    {
      id: 'riscos-jogo-responsavel',
      title: '7. Assunção consciente dos riscos e jogo responsável',
      paragraphs: [
        '7.1 O Usuário reconhece que apostas podem causar perda parcial ou total dos valores utilizados e que nenhuma Análise elimina o risco inerente ao evento esportivo.',
        '7.2 Qualquer decisão de apostar é pessoal, voluntária e independente. O Usuário deve avaliar se a prática é legal em sua localidade e se possui capacidade financeira para suportar integralmente uma eventual perda.',
        '7.3 O Usuário não deve utilizar valores necessários à subsistência, moradia, alimentação, saúde, educação, impostos, dívidas ou obrigações familiares, nem dinheiro emprestado ou obtido mediante crédito.',
        '7.4 O Usuário não deve apostar para recuperar perdas, sob pressão, em sequência compulsiva, sob influência de álcool ou drogas, ou em situação de comprometimento emocional, ansiedade intensa, impulsividade ou dificuldade de autocontrole.',
        '7.5 O Usuário deve estabelecer limites de tempo e orçamento fora da Plataforma, revisar seus gastos e interromper o uso se perceber sinais de comportamento prejudicial.',
        '7.6 A suspensão voluntária ainda não existe na aplicação e é uma funcionalidade recomendada. A ausência desse recurso não impede o Usuário de cancelar a Assinatura, excluir a Conta ou solicitar bloqueio de marketing pelos canais oficiais.',
        '7.7 O Serviço não substitui atendimento médico ou psicológico. Pessoas com dificuldade de controlar apostas devem buscar ajuda profissional e serviços públicos de saúde mental, como a Rede de Atenção Psicossocial e os CAPS, conforme disponibilidade local.',
        '7.8 O Fornecedor não direcionará comunicação comercial a menores e não permitirá o uso do produto como promessa de renda, solução de dívida, emprego, enriquecimento ou recuperação de perdas.',
      ],
    },
    {
      id: 'perdas-financeiras',
      title: '8. Perdas financeiras e resultados esportivos',
      paragraphs: [
        '8.1 O Fornecedor não participa da decisão de apostar, não recebe ou registra apostas, não controla o valor apostado, não guarda recursos destinados a apostas e não executa apostas em nome do Usuário.',
        '8.2 O Fornecedor não controla a casa de apostas escolhida pelo Usuário, suas regras, limites, odds, mercados, liquidação, saques, depósitos, bloqueios, encerramento de conta ou disponibilidade.',
        '8.3 O Fornecedor não controla o resultado de eventos esportivos e não responde, na extensão permitida por lei, por perdas financeiras decorrentes de decisões autônomas de aposta tomadas e executadas pelo Usuário.',
        '8.4 Não são reembolsáveis pelo Fornecedor valores perdidos em plataformas de terceiros. A Assinatura do SaaS não inclui seguro, cobertura, compensação, banca, crédito ou garantia por perdas.',
        '8.5 A divergência entre o resultado real e uma Probabilidade ou Predição não cria, por si só, direito a indenização, reembolso da Assinatura ou compensação de aposta.',
        '8.6 Na extensão permitida por lei, o Fornecedor não responde por lucros cessantes calculados com base em resultado esportivo esperado, aposta supostamente não realizada, alteração de odds, mercado indisponível ou hipótese de ganho que o Usuário afirma que teria obtido.',
        '8.7 Esta seção não afasta responsabilidade por defeito comprovadamente imputável ao próprio Serviço, cobrança indevida, dolo, fraude, violação da LGPD, falha de segurança imputável ao Fornecedor ou outra obrigação que não possa ser excluída por lei. A existência de defeito e o nexo causal serão avaliados conforme a legislação aplicável e as circunstâncias do caso.',
      ],
    },
    {
      id: 'ausencia-vinculo',
      title: '9. Ausência de vínculo com casas de apostas',
      paragraphs: [
        '9.1 Conforme a configuração verificada nesta versão do código, o BetIntel AI não é casa de apostas, não recebe apostas, não mantém carteira de apostador, não processa saques ou depósitos e não controla contas mantidas em terceiros.',
        '9.2 O Fornecedor não garante a legalidade, segurança, solvência ou regularidade de plataformas externas escolhidas pelo Usuário. O Usuário deve verificar se eventual operador é autorizado e se seu uso é permitido em sua localidade.',
        '9.3 Não foi encontrado vínculo, patrocínio, parceria, publicidade ou comissão com operador de apostas no repositório auditado. Qualquer mudança deve ser informada de forma clara, destacada e verificável e exige revisão destes Termos.',
        '9.4 Marcas, campeonatos, clubes, federações e serviços de terceiros eventualmente citados pertencem aos respectivos titulares. A citação descritiva não implica endosso.',
        '9.5 ATENÇÃO: se houver link de afiliado, publicidade, código promocional, comissão, remuneração por cadastro, depósito, volume, atividade ou perda do Usuário, esta cláusula deve ser substituída por versão específica e o lançamento deve ser submetido a revisão regulatória adicional.',
      ],
    },
    {
      id: 'dados-esportivos',
      title: '10. Dados esportivos e fornecedores externos',
      notice: '[EXIGE VALIDAÇÃO DE LICENÇA COMERCIAL DOS DADOS ANTES DA PUBLICAÇÃO DEFINITIVA]',
      paragraphs: [
        '10.1 Determinados Dados Esportivos podem ser fornecidos por [FORNECEDORES DE DADOS ESPORTIVOS] ou outras fontes identificadas na Plataforma.',
        '10.2 Dados de terceiros podem apresentar atrasos, indisponibilidades, duplicidades, correções, divergências de classificação, mudança de identificadores ou diferenças metodológicas.',
        '10.3 Partidas podem ser adiadas, canceladas, interrompidas, alteradas, remarcadas ou ter resultados e estatísticas corrigidos posteriormente. Fontes diferentes podem atribuir cartões, escanteios, assistências e outros eventos de modo distinto.',
        '10.4 O Fornecedor adotará esforços razoáveis e proporcionais para validar, monitorar e corrigir os dados, sem garantir atualização em tempo real, salvo compromisso expresso no Plano ou SLA específico.',
        '10.5 O Usuário deve conferir informações sensíveis ao tempo em fontes oficiais antes de qualquer decisão. A Plataforma exibirá, quando disponível, data e hora de atualização e categoria da fonte.',
        '10.6 A licença do Serviço não concede ao Usuário direitos sobre bases ou marcas de terceiros além do necessário ao uso autorizado.',
        '10.7 O Fornecedor somente utilizará dados de terceiros dentro das licenças aplicáveis. Os contratos dos fornecedores devem autorizar expressamente armazenamento, transformação, exibição comercial, derivados, exportação e treinamento de modelos quando essas atividades existirem.',
      ],
    },
    {
      id: 'conta-seguranca',
      title: '11. Conta, credenciais e segurança',
      paragraphs: [
        '11.1 O Usuário deve fornecer dados verdadeiros, completos e atualizados e utilizar Conta individual.',
        '11.2 Credenciais são pessoais e intransferíveis. É proibido compartilhar, vender, ceder, alugar ou permitir uso simultâneo por pessoas não autorizadas.',
        '11.3 O Usuário deve adotar senha forte, proteger seu dispositivo, encerrar sessões em equipamentos compartilhados e habilitar autenticação multifator quando disponível.',
        '11.4 Ações realizadas após autenticação serão atribuídas à Conta, sem prejuízo da análise de fraude, falha de segurança e responsabilidade efetiva.',
        '11.5 O Usuário deve comunicar imediatamente acesso indevido, perda de dispositivo, suspeita de fraude ou comprometimento de credenciais pelo [E-MAIL DE SUPORTE].',
        '11.6 O Fornecedor poderá encerrar sessões, exigir redefinição de senha, bloquear ações críticas ou suspender preventivamente a Conta quando houver risco razoável de fraude, segurança ou violação, comunicando o Usuário e permitindo regularização quando cabível.',
        '11.7 O Usuário não será responsabilizado automaticamente por evento decorrente de falha de segurança imputável ao Fornecedor. O compartilhamento voluntário de credenciais poderá ser considerado na apuração do nexo causal e das medidas aplicáveis.',
      ],
    },
    {
      id: 'organizacoes',
      title: '12. Organizações e equipes',
      paragraphs: [
        '12.1 Planos organizacionais podem disponibilizar papéis de Proprietário, Administrador, Membro e Somente Leitura, conforme os recursos reais da Plataforma.',
        '12.2 Quem cria ou contrata uma Organização declara possuir poderes para representá-la e para convidar membros.',
        '12.3 O Proprietário e os Administradores são responsáveis por gerenciar convites, permissões, remoções, acesso a Conteúdo compartilhado e conformidade interna, dentro dos limites do sistema e da lei.',
        '12.4 A Organização deve informar seus membros sobre o uso do Serviço, as políticas aplicáveis e o tratamento de dados realizado por ela. Quando atuar como controladora e o Fornecedor como operador, as partes deverão celebrar acordo de tratamento de dados.',
        '12.5 Convites devem ser enviados somente a pessoas autorizadas. O convidado deverá aceitar estes Termos e a Política de Privacidade antes do acesso. O administrador não aceita automaticamente obrigações pessoais em nome de cada membro.',
        '12.6 A remoção de um membro encerra seu acesso à Organização, mas não necessariamente exclui a Conta individual ou registros que devam ser mantidos por obrigação legal, segurança ou auditoria.',
        '12.7 A transferência de propriedade exigirá confirmação reforçada e poderá depender de verificação de identidade, situação de pagamento e ausência de disputa.',
        '12.8 Os limites de assentos e recursos são os do Plano. Excedentes serão bloqueados ou cobrados apenas se houver preço e autorização claros antes da utilização.',
        '12.9 No encerramento da Organização, os dados serão exportados, excluídos, anonimizados ou retidos conforme [PRAZO DE RETENÇÃO], contrato empresarial e Política de Privacidade.',
      ],
    },
    {
      id: 'planos-assinatura',
      title: '13. Planos, preços e assinatura',
      notice: 'O billing real permanece bloqueado pelos gates comercial, jurídico, fiscal e de licenciamento de dados. Nenhuma contratação está disponível nesta minuta.',
      paragraphs: [
        '13.1 Os Planos, recursos, limites, assentos, ciclo de cobrança, suporte, preço, moeda, impostos e condições vigentes serão exibidos antes da contratação na página de Planos.',
        '13.2 Planos disponíveis: [PLANOS DISPONÍVEIS]. Valores: [VALORES]. Essas informações devem corresponder ao comportamento real do gateway e ao documento fiscal.',
        '13.3 A Assinatura poderá ser mensal, anual ou por prazo específico, conforme selecionado. A renovação recorrente ocorrerá somente após autorização clara e destacada do contratante.',
        '13.4 Ao contratar, o Usuário autorizará o meio de pagamento a realizar as cobranças do ciclo selecionado, inclusive tentativas razoáveis após falha, sem cobrança duplicada ou alteração não informada.',
        '13.5 Se houver período de teste, serão informados duração, recursos, necessidade de cartão, data da primeira cobrança, forma de cancelamento e consequências do término. Não haverá conversão silenciosa em plano pago sem informação e consentimento compatíveis.',
        '13.6 Cupons e promoções terão regras, prazo, público, preço após a promoção e limitações apresentados antes da contratação.',
        '13.7 Upgrades podem produzir cobrança imediata proporcional se o gateway suportar e o Usuário confirmar o valor. Downgrades normalmente terão efeito no ciclo seguinte, salvo indicação diferente.',
        '13.8 Proration, créditos, excedentes e ajustes somente serão aplicados conforme regra previamente exibida e suportada pelo gateway.',
        '13.9 Em caso de inadimplência, o Fornecedor poderá notificar, restringir recursos e suspender a Conta após prazo razoável de regularização, preservando acesso a recibos, cancelamento e canais de suporte.',
        '13.10 A reativação poderá exigir quitação de valores legítimos e nova autorização de pagamento. Cobranças contestadas de boa-fé serão apuradas antes de medidas desproporcionais.',
        '13.11 O cancelamento impede renovações futuras e, salvo arrependimento, defeito, cobrança indevida ou política mais favorável, o acesso permanecerá até o fim do período já pago.',
        '13.12 Alterações de preço serão comunicadas previamente e valerão a partir do ciclo seguinte, permitindo cancelamento antes da cobrança. Para consumidores, a comunicação deve ser clara, destacada e em prazo razoável; para contratos empresariais, observar-se-á o instrumento específico.',
      ],
    },
    {
      id: 'cancelamento-reembolso',
      title: '14. Direito de arrependimento, cancelamento, reembolso e chargeback',
      notice: '[VALIDAR COM ADVOGADO E COM O GATEWAY DE PAGAMENTO]',
      paragraphs: [
        '14.1 O consumidor que contratar à distância poderá exercer o direito de arrependimento no prazo legal aplicável, contado da contratação, pelos mesmos canais de facilidade usados para contratar e pelos canais de suporte.',
        '14.2 Como opção conservadora para publicação no Brasil, o pedido feito dentro de 7 dias será reembolsado integralmente ao consumidor, inclusive quando o acesso digital tiver iniciado, sem prejuízo de regra legal superveniente ou orientação jurídica específica.',
        '14.3 Não será exigida renúncia genérica ao direito de arrependimento. Qualquer alternativa que preveja retenção proporcional por uso imediato de conteúdo digital deve ser validada por advogado à luz do modelo, das telas e da interpretação aplicável, antes de ser adotada.',
        '14.4 Após o prazo de arrependimento, o cancelamento interrompe renovações futuras. Reembolso do ciclo em andamento seguirá [POLÍTICA DE REEMBOLSO], sem afastar hipóteses de defeito do Serviço, descumprimento da oferta, cobrança indevida ou duplicada.',
        '14.5 Cobranças indevidas ou duplicadas serão apuradas e restituídas conforme a legislação, sem condicionamento a crédito interno quando o reembolso em dinheiro for devido.',
        '14.6 Antes de iniciar chargeback, recomenda-se que o Usuário contate o suporte para solução rápida, sem que isso limite seu direito de contestar a cobrança perante o meio de pagamento ou autoridades competentes.',
        '14.7 Chargeback manifestamente fraudulento ou referente a serviço efetivamente prestado poderá resultar em suspensão preventiva, cobrança do valor legítimo e apresentação de evidências ao gateway, assegurada oportunidade de esclarecimento.',
        '14.8 O prazo de processamento do estorno depende do meio de pagamento e será informado na confirmação, sem prometer data que o Fornecedor não controla.',
      ],
    },
    {
      id: 'uso-aceitavel',
      title: '15. Uso aceitável',
      paragraphs: [
        '15.1 O Usuário utilizará a Plataforma de forma lícita, ética e compatível com estes Termos, a Política de Uso Aceitável, direitos de terceiros e limites do Plano.',
        '15.2 É proibido praticar fraude, invasão, tentativa de acesso não autorizado, exploração de vulnerabilidade, interferência, malware, engenharia social ou burla de controles.',
        '15.3 É proibido criar contas abusivas, compartilhar credenciais, contornar limites, automatizar acessos fora da API autorizada, realizar scraping, crawling, extração em massa ou sobrecarregar a infraestrutura.',
        '15.4 É proibido copiar, republicar, revender, sublicenciar, disponibilizar publicamente ou reproduzir sistematicamente Análises e bancos de dados, salvo autorização escrita.',
        '15.5 É proibido usar o Conteúdo para treinar, avaliar ou aperfeiçoar sistema concorrente, criar produto substituto, realizar engenharia reversa ou reconstruir modelos, salvo hipótese legal irrenunciável.',
        '15.6 É proibido apresentar as Análises como garantia de lucro, certificação, recomendação individual ou conteúdo próprio, bem como enganar, assediar ou causar dano a terceiros.',
        '15.7 É proibido utilizar a Plataforma em jurisdição onde o uso seja ilegal ou para facilitar apostas ilegais, intermediação, execução para terceiros ou operação sem autorização.',
        '15.8 Testes de segurança exigem autorização escrita e escopo definido. Relatos de vulnerabilidade devem seguir [POLÍTICA DE DIVULGAÇÃO RESPONSÁVEL].',
      ],
    },
    {
      id: 'propriedade-intelectual',
      title: '16. Propriedade intelectual e licença',
      paragraphs: [
        '16.1 O software, código, documentação, marca, identidade visual, seleção e organização de Conteúdo, interfaces, modelos próprios e materiais originais pertencem ao Fornecedor ou a seus licenciantes, conforme aplicável.',
        '16.2 O Usuário recebe licença limitada, revogável, não exclusiva, intransferível e não sublicenciável para acessar o Serviço durante a vigência da Assinatura e dentro do Plano.',
        '16.3 A licença não transfere titularidade e não autoriza cópia, descompilação, engenharia reversa, concorrência parasitária, remoção de avisos, exploração comercial ou criação de derivado, salvo autorização ou direito legal irrenunciável.',
        '16.4 Dados públicos, fatos esportivos, marcas e bases de terceiros não são reivindicados como propriedade do Fornecedor além dos direitos efetivamente detidos sobre seleção, organização, transformação, software e conteúdo original.',
        '16.5 Conteúdo inserido pelo Usuário permanece de sua titularidade ou de seu legítimo titular. O Usuário concede licença limitada ao Fornecedor para hospedar, processar, transmitir e exibir esse conteúdo apenas para prestar, proteger e melhorar o Serviço, conforme a Política de Privacidade e o contrato empresarial.',
        '16.6 Sugestões e feedback podem ser utilizados para melhorar o produto sem obrigação de remuneração, desde que não revelem informação confidencial nem transfiram indevidamente direitos sobre conteúdo do Usuário.',
        '16.7 O Usuário deve respeitar marcas e direitos de terceiros. Notificações de violação serão recebidas em [CANAL DE PROPRIEDADE INTELECTUAL] com informações suficientes para análise.',
      ],
    },
    {
      id: 'disponibilidade',
      title: '17. Disponibilidade, manutenção e suporte',
      paragraphs: [
        '17.1 O Fornecedor buscará manter o Serviço disponível de forma razoável, mas não garante funcionamento ininterrupto, livre de erros ou adequado a toda finalidade particular.',
        '17.2 Poderão ocorrer manutenções programadas, correções, atualizações e intervenções emergenciais. Quando viável, manutenções relevantes serão comunicadas em [CANAL DE STATUS].',
        '17.3 A disponibilidade depende de provedores de nuvem, telecomunicações, autenticação, gateway, e-mail, dados e outros terceiros. O Fornecedor responderá por sua própria diligência e por obrigações legais, sem assumir controle sobre toda falha externa.',
        '17.4 SLA somente se aplica a Plano ou contrato que o preveja expressamente, com métrica, exclusões, janela de medição, créditos e procedimento definidos.',
        '17.5 Falhas causadas por dispositivo, conexão, configuração, credenciais, software de terceiros ou uso incompatível pelo Usuário não são indisponibilidade geral do Serviço.',
        '17.6 O prazo estimado de suporte é [PRAZO DE RESPOSTA DO SUPORTE], sem garantia de solução no mesmo prazo, salvo SLA específico.',
      ],
    },
    {
      id: 'alteracoes-produto',
      title: '18. Alterações no produto',
      paragraphs: [
        '18.1 O Fornecedor poderá corrigir, evoluir, incluir, retirar, substituir ou reorganizar funcionalidades, layout, modelos, fornecedores e integrações para segurança, desempenho, conformidade ou evolução do produto.',
        '18.2 Alterações que não reduzam materialmente o Plano podem ser implementadas durante a vigência.',
        '18.3 Quando a alteração reduzir materialmente recurso essencial de Plano pago, aumentar preço, modificar obrigações do Usuário, afetar tratamento de dados ou exigir novo consentimento, haverá comunicação prévia e medida adequada, que poderá incluir migração, crédito, cancelamento sem renovação ou outra solução proporcional.',
        '18.4 Recursos beta, experimentais ou gratuitos podem ser alterados ou descontinuados com menor antecedência, desde que isso seja informado e não contrarie oferta vinculante.',
      ],
    },
    {
      id: 'suspensao-encerramento',
      title: '19. Suspensão e encerramento',
      paragraphs: [
        '19.1 O Fornecedor poderá suspender ou limitar acesso por violação destes Termos, fraude, risco de segurança, inadimplência, ordem judicial, exigência legal, uso ilegal ou risco relevante a terceiros.',
        '19.2 A medida será proporcional ao risco e, quando cabível, precedida de aviso e oportunidade de correção ou esclarecimento.',
        '19.3 Suspensões emergenciais poderão ser imediatas quando necessárias para impedir dano, fraude, ataque ou descumprimento legal, com comunicação posterior razoável.',
        '19.4 O Usuário pode cancelar a Assinatura e solicitar exclusão da Conta pelos canais indicados. A exclusão não impede retenção necessária para obrigação legal, exercício de direitos, prevenção à fraude, segurança, cobrança legítima ou defesa em processo.',
        '19.5 Antes do encerramento empresarial, a Organização poderá exportar dados conforme recursos do Plano e prazo de [PRAZO DE EXPORTAÇÃO].',
        '19.6 No encerramento definitivo do Serviço pelo Fornecedor, usuários pagos serão avisados com antecedência razoável e receberão solução proporcional quanto ao período não utilizado, salvo impossibilidade legal ou evento de força maior devidamente justificado.',
        '19.7 Os efeitos sobre valores pagos dependerão da causa. Violação grave imputável ao Usuário não gera automaticamente reembolso, mas a retenção não poderá ser abusiva ou superior ao dano e ao serviço efetivamente prestado, quando a lei exigir proporcionalidade.',
      ],
    },
    {
      id: 'responsabilidade',
      title: '20. Limitação e alocação de responsabilidade',
      paragraphs: [
        '20.1 A. Riscos inerentes. O Fornecedor não controla a ocorrência de resultados esportivos. A divergência entre previsão e resultado integra o risco inerente a modelos probabilísticos e não caracteriza, isoladamente, defeito.',
        '20.2 B. Decisões autônomas. Na máxima extensão permitida por lei, o Fornecedor não responde por perdas em apostas, apostas não realizadas, supostos ganhos, gestão de banca, decisões tomadas exclusivamente com base nas Análises ou uso incompatível com avisos claros.',
        '20.3 C. Terceiros. O Fornecedor não responde por atos de operadores de apostas, encerramento de contas externas, alteração de odds, indisponibilidade de mercados, regras de liquidação ou falhas de terceiros fora de seu controle, sem prejuízo de sua responsabilidade por escolha, integração ou informação quando legalmente imputável.',
        '20.4 D. Indisponibilidade. Interrupções programadas, emergenciais ou externas serão tratadas conforme o Plano, o SLA e a legislação. Não há garantia absoluta de continuidade.',
        '20.5 E. Danos indiretos. Em relações empresariais e na extensão permitida por lei, ficam excluídos danos indiretos, consequenciais, perda de oportunidade especulativa e lucros cessantes baseados em resultado esportivo esperado, salvo quando decorrentes de conduta ou obrigação que não possa ser limitada.',
        '20.6 F. Limite financeiro B2B. Para Organizações e Usuários Profissionais em contratação empresarial válida, a responsabilidade agregada do Fornecedor por danos diretos poderá ser limitada ao total pago pelo contratante nos 12 meses anteriores ao evento, ou [LIMITE NEGOCIADO], o que for aplicável. Esse limite não se aplica automaticamente a consumidores.',
        '20.7 G. Responsabilidades preservadas. Nenhuma disposição limita responsabilidade por dolo, fraude, culpa grave quando não limitável, descumprimento de obrigação legal, violação de direitos do consumidor, cobrança indevida, violação da LGPD, falha de segurança imputável ao Fornecedor, danos pessoais, violação de propriedade intelectual pelo próprio Fornecedor ou defeito comprovadamente imputável ao Serviço, na medida em que a lei não permita exclusão.',
        '20.8 A responsabilidade será apurada conforme dano comprovado, nexo causal, contribuição de cada parte, dever de mitigação e legislação aplicável. Avisos de risco não legitimam serviço defeituoso ou informação enganosa.',
        '20.9 Para Usuários Consumidores, prevalecem as garantias e regras de responsabilidade obrigatórias do CDC. Qualquer interpretação destes Termos deverá preservar o equilíbrio e a boa-fé.',
      ],
    },
    {
      id: 'indenizacao',
      title: '21. Indenização por uso indevido',
      paragraphs: [
        '21.1 O Usuário será responsável por danos diretos comprovados que causar por ato ilícito, fraude, violação destes Termos, uso ilegal, infração de propriedade intelectual, revenda não autorizada, comprometimento intencional de segurança ou uso de identidade de terceiro.',
        '21.2 A obrigação será proporcional à conduta, ao nexo causal e ao dano, e não impõe ao consumidor responsabilidade ilimitada, automática ou por atos fora de seu controle.',
        '21.3 Organizações responderão pelos atos de seus administradores e membros dentro dos poderes e do uso corporativo, sem excluir responsabilidade individual do agente nem deveres próprios do Fornecedor.',
        '21.4 O Fornecedor comunicará reclamações relevantes e permitirá participação razoável na defesa, salvo urgência, sigilo legal ou conflito de interesses.',
      ],
    },
    {
      id: 'privacidade',
      title: '22. Privacidade e proteção de dados',
      paragraphs: [
        '22.1 O tratamento de dados pessoais é descrito na Política de Privacidade, que integra estes Termos para fins informativos, sem consentimento genérico para qualquer tratamento.',
        '22.2 Em regra, o Fornecedor atua como controlador dos dados de cadastro, segurança, faturamento, suporte, comunicação transacional, prevenção à fraude e gestão da relação. Em contextos empresariais, poderá atuar como operador em relação a dados inseridos pela Organização, conforme contrato.',
        '22.3 As finalidades essenciais incluem criar Conta, autenticar, entregar o Plano, cobrar, emitir comprovantes, atender suporte, proteger a segurança, cumprir obrigações e melhorar o Serviço com bases legais adequadas.',
        '22.4 O Usuário poderá exercer direitos pelo [E-MAIL DE PRIVACIDADE] ou [CANAL DO TITULAR]. O Fornecedor poderá verificar identidade e responder nos prazos legais.',
        '22.5 Fornecedores relevantes de hospedagem, pagamento, dados, e-mail, analytics, suporte, antifraude e IA serão identificados na Política de Privacidade na medida necessária à transparência.',
        '22.6 Registros de acesso e logs serão tratados conforme o Marco Civil, a LGPD, segurança, prevenção à fraude e prazos aplicáveis.',
        '22.7 Transferências internacionais, quando houver, utilizarão mecanismo válido e serão informadas, inclusive cláusulas-padrão da ANPD ou decisão de adequação aplicável.',
        '22.8 Se houver decisão automatizada que afete interesses do Usuário, a Política explicará critérios e mecanismos de revisão aplicáveis. A mera geração de probabilidade esportiva não deve ser rotulada como decisão sobre o titular sem análise do fluxo real.',
        '22.9 Incidentes com risco ou dano relevante serão avaliados e comunicados conforme a LGPD e a regulamentação da ANPD. O Fornecedor manterá processo de resposta, registros e contratos de notificação com operadores.',
        '22.10 O canal do encarregado ou responsável pela privacidade é [NOME OU CANAL DO ENCARREGADO], sem presumir a existência de DPO formal quando a organização estiver sujeita a regime simplificado ou ainda não tiver designado pessoa específica.',
      ],
    },
    {
      id: 'comunicacoes',
      title: '23. Comunicações',
      paragraphs: [
        '23.1 Comunicações necessárias ao Serviço poderão ser enviadas por e-mail, notificações na Plataforma, telefone quando autorizado ou outro canal informado pelo Usuário.',
        '23.2 Mensagens transacionais incluem segurança, cobrança, recibos, suporte, cancelamento, alterações contratuais, incidentes e manutenção. Elas não dependem de consentimento de marketing quando necessárias à relação.',
        '23.3 Mensagens comerciais exigem base legal e opção compatível. O opt-in de marketing será separado, não pré-marcado, e poderá ser revogado facilmente.',
        '23.4 A revogação de marketing não impede comunicações essenciais. Usuários autoexcluídos ou que solicitem bloqueio relacionado a jogo responsável não devem receber campanhas incompatíveis com a solicitação.',
        '23.5 O Usuário deve manter seus contatos atualizados. Alterações materiais dos Termos serão destacadas e não escondidas em newsletter genérica.',
      ],
    },
    {
      id: 'lei-conflitos',
      title: '24. Lei aplicável e resolução de conflitos',
      paragraphs: [
        '24.1 Estes Termos são regidos pela legislação brasileira.',
        '24.2 Para Usuários Consumidores, fica preservado o foro legalmente competente, inclusive o foro do domicílio do consumidor. A tentativa de solução administrativa é facultativa e não impede acesso ao Judiciário, órgãos de defesa ou plataformas públicas de resolução.',
        '24.3 Para contratos empresariais efetivos, as partes elegem o foro de [CIDADE E ESTADO], salvo norma imperativa ou negociação diversa no contrato específico.',
        '24.4 Mediação poderá ser utilizada por acordo posterior. Arbitragem somente será aplicável a relação B2B mediante cláusula específica, destacada e validamente aceita, não sendo imposta automaticamente ao consumidor em contrato de adesão.',
      ],
    },
    {
      id: 'disposicoes-gerais',
      title: '25. Disposições gerais',
      paragraphs: [
        '25.1 Se uma disposição for inválida, as demais permanecerão vigentes e a cláusula será interpretada ou substituída de modo compatível com a lei e sua finalidade legítima.',
        '25.2 A tolerância não constitui renúncia. Direitos irrenunciáveis permanecem preservados.',
        '25.3 O Usuário não pode ceder a Conta ou o contrato sem autorização. O Fornecedor poderá reorganizar sua estrutura ou ceder o contrato em operação societária, desde que preserve direitos, informe quando necessário e observe a LGPD.',
        '25.4 A versão em português prevalece para usuários no Brasil. Traduções terão caráter informativo, salvo acordo específico.',
        '25.5 Estes Termos, a Política de Privacidade, a Política de Uso Aceitável, a Política de Cancelamento e a oferta apresentada compõem o contrato, observada a prevalência da condição mais favorável ao consumidor quando legalmente aplicável.',
      ],
    },
    {
      id: 'versao-historico',
      title: '26. Versão, vigência e histórico',
      paragraphs: [
        '26.1 Versão: 0.9 - minuta. Publicação: [DATA DE PUBLICAÇÃO]. Vigência: [DATA DE VIGÊNCIA].',
        '26.2 Alterações serão registradas em histórico com data, resumo e indicação de impacto.',
        '26.3 Mudanças materiais serão comunicadas previamente e poderão exigir novo aceite. Mudanças corretivas, formais ou favoráveis poderão entrar em vigor com comunicação simples.',
        '26.4 Versões anteriores permanecerão acessíveis no histórico desta página e a versão aceita pelo Usuário poderá ser baixada em sua Conta.',
        '26.5 Contato para dúvidas contratuais: [E-MAIL DE SUPORTE].',
      ],
    },
  ],
}

